[tool.poetry]
name = "renshu-repo-01"
version = "0.1.0"
description = ""
authors = ["jpibukiuchiyama <itkids0702@panepla.or.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
